### ISSUE TITLE
add functionality which flags potential issues before aggregation

### ISSUE THREAD

**Issue by naomi-henderson** [pangeo-data/esgf2xarray#6]
The `files` dataframe returned by `esgf_search` is ideal for identifying issues which might arise during aggregation. For example, there can be both r*i1p1f1 and r*i1p1f2 type ensemble members which should probably not be combined. Or, if there are two versions (v20190101 and v20190202, so use the latest) of the same file or if one ensemble member covers only a subset of the time it would be good to flag these issues before aggregation.  

I am keeping track of all the anomalies I see in the CMIP6 data and propose to write a new function to check `files` , flagging potential issues so the they can be dealt with on a case by case basis rather than silently dealing with them in `combine_files`.

**Comment by rabernat** [comment]
Great point. There are already some ad-hoc checks like this in the code. For example, I drop duplicate checksums:

https://github.com/pangeo-data/esgf2xarray/blob/624d66d2036e92c65c9885fd9a7e7fd9aa884d93/esgf2zarr/search.py#L73

I totally agree with the idea of putting these checks in a standalone function. Perhaps we could also use [warnings](https://docs.python.org/3/library/warnings.html) to be verbose about what problems are found, rather than just silently fixing them.

**Comment by naomi-henderson** [comment]
I think we need to move the drop_duplicate checksums to `esgf_search` after appending the pages.  I just had an example of a multi-page search in which the duplicates were on different pages and didn't get dropped.

So I propose moving the `.drop_duplicates(subset='checksum')` from return statement of `_get_page_dataframe` to the return of `esgf_search`:

https://github.com/pangeo-data/esgf2xarray/blob/624d66d2036e92c65c9885fd9a7e7fd9aa884d93/esgf2zarr/search.py#L135

**Comment by rabernat** [comment]
Go for it!

If you would like me to look at any code, make a pull request. Otherwise just push to master.

**Comment by naomi-henderson** [comment]
Another check needed, putting it here just so I don't forget:
- when combining variables, check to see if time grid has same units (days since ...) and is, in overlapping time periods, on the same grid (e.g., in CMIP6, 3 hourly pr is at 1:30a, 4:30a, etc and 3 hourly tas,huss is at 3a, 6a, etc) - otherwise we will have to have two separate time grids or DON'T COMBINE
